on:
  push:
    branches:
    - 'main'

permissions:
  id-token: write
  contents: read

name: Prod Deployment



jobs:
  development:
    name: 'Deploy Development'
    runs-on: ubuntu-latest
    environment: dev
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VERSION: 1.3.6
      TF_VAR_ENV: ${{ vars.ENV }}
    
    strategy:
      matrix:
        folder: ['dev', 'prod']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform -chdir=${{ matrix.folder }} init

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=${{ matrix.folder }} plan -no-color -var environment=$TF_VAR_ENV

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=${{ matrix.folder }} apply -auto-approve

  