on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

name: On Release Main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: prod
    env:
      TF_VERSION: 1.3.6

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
